defaults:
  - dataset: hbm_ocean
  - domain: baltic_sea
  - _self_

save_to: data
output_suffix: ""  # // e.g. "_test2" via CLI override
output_path: ${save_to}/${dataset.source}_${domain.name}${output_suffix}
verbose: false
mode: run  # // one of: run, dry_run, check, rechunk


# //log format//
hydra:
  job_logging:
    formatters:
      simple:
        format: '%(asctime)s %(levelname)-7s %(message)s'
        datefmt: '%H:%M:%S'